spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=hiber
    username: postgres
    password: ***
  jpa:
    show-sql: true
    properties:
      hibernate.current_session_context_class: thread
server:
  port: 8189
